def get_top_50():
    return [
    # POS FEATURES
    "RatioPronoun", 
    "NP_to_PRP", 
    # "", 
    "NumAdverbs", 
    "ADVP_to_RB", 
    "VP_to_VBG_PP", 
    # "VP_to_IN_S", Need to locate this feature
    "VP_to_AUX_ADJP", 
    "VP_to_AUX_VP", 
    "VP_to_VBG", 
    "VP_to_AUX", 
    "VP_to_VBD_NP", 
    "INTJ_to_UH", 
    "NP_to_DT_NN", 
    "proportion_below_threshold_0.5", 
    "NumVerbs", 
    "NumNouns", 
    "MeanWordLength", 
    "HonoreStatistic", 
    "NumInflectedVerbs", 
    "avg_cos_dist", 
    "VPTypeRate", 
    "PProportion", 
    "PPTypeRate", 
    # InfoUnits
    "keywordIUObjectWindow", 
    "binaryIUObjectWindow", 
    "keywordIUObjectSink", 
    "binaryIUObjectSink", 
    "keywordIUObjectCookie", 
    "binaryIUObjectCookie", 
    "keywordIUObjectCurtains", 
    "binaryIUObjectCurtains", 
    "binaryIUSubjectGirl", 
    "binaryIUObjectDishes", 
    "keywordIUObjectStool", 
    "binaryIUObjectStool", 
    "keywordIUSubjectWoman", 
    "binaryIUSubjectWoman", 
    # PsychoLing
    "getFamiliarityScore", 
    "getConcretenessScore", 
    "getImagabilityScore", 
    "getAoaScore", 
    "getSUBTLWordScores", 
    "getLightVerbCount", 
    # Acoustic 
    "mfcc1_skewness",
    "mfcc2_skewness",
    "mfcc8_skewness",
    "mfcc12_skewness",
    "mfcc5_kurtosis",
    "mfcc3_vel_kurtosis"
    ]
    